version: '3'

services:

  protos_go:
    container_name: protos_go
    build:
      context: ../
      dockerfile: ./build/go/Dockerfile
    volumes:
      - "../gen/go:/app/gen/go"
    networks:
      - my_network
    command: protoc -I proto proto/anime/anime.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
    restart: "no"

networks:
  my_network:
    driver: bridge